export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const CLEAR_USER_LOADING = "CLEAR_USER_LOADING";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const GET_USER_PRESET = "GET_USER_PRESET";

// Surplus
export const CREATE_SURPLUS = "CREATE_SURPLUS";
export const ACTIVATE_SURPLUS = "ACTIVATE_SURPLUS";
export const GET_SURPLUSES = "GET_SURPLUSES";
export const GET_CURRENT_USER_SURPLUSES = "GET_CURRENT_USER_SURPLUSES";
export const GET_SURPLUS = "GET_SURPLUS";
export const GET_SURPLUS_KEYWORDS = "GET_SURPLUS_KEYWORDS";
export const DELETE_SURPLUS = "DELETE_SURPLUS";
export const UPDATE_SURPLUS = "UPDATE_SURPLUS";
export const SET_SURPLUS_LOADING = "SET_SURPLUS_LOADING";
export const CLEAR_SURPLUS_LOADING = "CLEAR_SURPLUS_LOADING";
// Job
export const CREATE_JOB = "CREATE_JOB";
export const ACTIVATE_JOB = "ACTIVATE_JOB";
export const GET_JOBS = "GET_JOBS";
export const GET_CURRENT_USER_JOBS = "GET_CURRENT_USER_JOBS";
export const GET_JOB = "GET_JOB";
export const GET_JOB_KEYWORDS = "GET_JOB_KEYWORDS";
export const DELETE_JOB = "DELETE_JOB";
export const UPDATE_JOB = "UPDATE_JOB";
export const SET_JOB_LOADING = "SET_JOB_LOADING";
export const CLEAR_JOB_LOADING = "CLEAR_JOB_LOADING";
export const GET_USER_JOBS = "GET_USER_JOBS";

// JOb Seeker
export const CREATE_JOB_SEEKER = "CREATE_JOB_SEEKER";
export const GET_JOB_SEEKERS = "GET_JOB_SEEKERS";
export const GET_JOB_SEEKER = "GET_JOB_SEEKER";
export const UPDATE_JOB_SEEKER = "UPDATE_JOB_SEEKER";
export const DELETE_JOB_SEEKER = "DELETE_JOB_SEEKER";
export const SET_JOB_SEEKER_LOADING = "SET_JOB_SEEKER_LOADING";
export const CLEAR_JOB_SEEKER_LOADING = "CLEAR_JOB_SEEKER_LOADING";
// Payment
export const PAYMENT_CHECKOUT = "PAYMENT_CHECKOUT";
