export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const CLEAR_USER_LOADING = "CLEAR_USER_LOADING";
export const SET_USER_LOADING = "SET_USER_LOADING";

// Surplus
export const CREATE_SURPLUS = "CREATE_SURPLUS";
export const ACTIVATE_SURPLUS = "ACTIVATE_SURPLUS";
export const GET_SURPLUSES = "GET_SURPLUSES";
export const GET_CURRENT_USER_SURPLUSES = "GET_CURRENT_USER_SURPLUSES";
export const GET_SURPLUS = "GET_SURPLUS";
export const GET_SURPLUS_NAMES = "GET_SURPLUS_NAMES";
export const DELETE_SURPLUS = "DELETE_SURPLUS";
export const UPDATE_SURPLUS = "UPDATE_SURPLUS";
export const SET_SURPLUS_LOADING = "SET_SURPLUS_LOADING";
export const CLEAR_SURPLUS_LOADING = "CLEAR_SURPLUS_LOADING";
